insert into Equipments (Description,QuantityTotal) values ('Black Magic 4K cinema',10)
insert into Equipments (Description,QuantityTotal) values ('Sony A6300',10)
insert into Equipments (Description,QuantityTotal) values ('Nikon D3200',10)
insert into Equipments (Description,QuantityTotal) values ('Nikon D3400',10)
insert into Equipments (Description,QuantityTotal) values ('Lens 14mm Ultra Wide-Angle f/2.8  for Canon EF Mount',10)
insert into Equipments (Description,QuantityTotal) values ('Lens 35mm T1.5 Cine Lens for Canon EF',10)
insert into Equipments (Description,QuantityTotal) values ('Lens 35mm Carl Ziess  Canon  f/2.8 Lens',10)
insert into Equipments (Description,QuantityTotal) values ('Lens 85mm Carl Ziess  Canon  f/2.8 Lens',10)
insert into Equipments (Description,QuantityTotal) values ('Lens 21mm Carl Ziess Canon  f/2.8 Lens',10)
insert into Equipments (Description,QuantityTotal) values ('Light Meter',10)
insert into Equipments (Description,QuantityTotal) values ('Tripod King Joy',10)
insert into Equipments (Description,QuantityTotal) values ('Tripod Libec',10)
insert into Equipments (Description,QuantityTotal) values ('Field Monitor 7" Pro On Camera',10)
insert into Equipments (Description,QuantityTotal) values ('1000w Fresnel Lights',10)
insert into Equipments (Description,QuantityTotal) values ('650w Fresnel Lights',10)
insert into Equipments (Description,QuantityTotal) values ('300w Fresnel Lights',10)
insert into Equipments (Description,QuantityTotal) values ('2000W Fresnel Lights',10)
insert into Equipments (Description,QuantityTotal) values ('HMI 200W Include barndoors,cables, plugs, blaster & Stand',10)
insert into Equipments (Description,QuantityTotal) values ('HMI 575W Include barndoors,cables, plugs, blaster & Stand',10)
insert into Equipments (Description,QuantityTotal) values ('HMI 1200W Include barndoors,cables, plugs, blaster & Stand',10)
insert into Equipments (Description,QuantityTotal) values ('HMI 2500W Include barndoors,cables, plugs, blaster & Stand',10)
insert into Equipments (Description,QuantityTotal) values ('Kino Flo Mini Car Kit',10)
insert into Equipments (Description,QuantityTotal) values ('Kino Flo Gaffer Kit + C-stand',10)
insert into Equipments (Description,QuantityTotal) values ('Runner 450 AW Backpack',10)
insert into Equipments (Description,QuantityTotal) values ('Shotgun Microphone',10)
insert into Equipments (Description,QuantityTotal) values ('Blimp & Boom Pole',10)
insert into Equipments (Description,QuantityTotal) values ('Pro Circumaural Closed-Back Monitor Headphones',10)
insert into Equipments (Description,QuantityTotal) values ('Tascam Field Recorder',10)
insert into Equipments (Description,QuantityTotal) values ('Zoom H6 Field Recorder',10)
insert into Equipments (Description,QuantityTotal) values ('Collar Lavalier',10)
